name: Päivitys Palkkasovellus

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Kloonaa repositorio
        uses: actions/checkout@v3

      - name: Päivitä HTML/CSS/JS-tiedostot
        run: |
          echo "<!DOCTYPE html><html><head><meta charset='UTF-8'><title>Test</title></head><body><h1>Päivitetty sisältö</h1></body></html>" > index.html
          echo "body { font-family: sans-serif; background: #eef; }" > style.css
          echo "console.log('Uusi versio ladattu');" > script.js

      - name: Commit ja push
        run: |
          git config user.name "ChatGPT Bot"
          git config user.email "chatgpt@auto.dev"
          git add .
          git commit -m "Automaattinen päivitys (index.html, style.css, script.js)" || echo "Ei muutoksia"
          git push
